title: Lifesine Music
iconURL: assets/logos/Lifesine_logo_sq_v2.0_(300x300).png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: tiddmeister
  github: Lifesine
  instagram: @LifesineMusic

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
#hyvor_talk_website_id: 14
#google_analytics: UA-NNNNNNNN-N