title: Lifesine Music
iconURL: assets/logos/ls_logo_sq_tr_300x300.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: tiddmeister
  github: Lifesine
#  instagram: @LifesineMusic

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
#hyvor_talk_website_id: 14
#google_analytics: UA-NNNNNNNN-N