title: Lifesine Music
# baseurl: beta.lifesinemusic.com

iconURL: assets/logos/ls_logo_wide_tr_v2_900x170.png
#logoURL: assets/logos/ls_logo_wide_v2_1000x300.png
logoURL: assets/logos/ls_logo_wide_tr_v2_900x170.png
theme: jekyll-theme-leaf
artURL: /assets/mix-artwork/


# for a clean URL
permalink: :slug

social:
  twitter: tiddmeister
  github: Lifesine
  soundcloud: Lifesine

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
#hyvor_talk_website_id: 14
#google_analytics: UA-NNNNNNNN-N